apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce-master
  labels:
    app: service-discovery
    environment: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        environment: master
    spec:
      containers:
      - name: service-discovery
        image: selimhorri/service-discovery-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8761
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "master"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 45
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-service
  namespace: ecommerce-master
  labels:
    app: service-discovery
    environment: master
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    app: service-discovery 