apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ecommerce-master
  labels:
    app: shipping-service
    environment: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
        environment: master
    spec:
      containers:
      - name: shipping-service
        image: selimhorri/shipping-service-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8084
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "master"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-discovery-service:8761/eureka"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service-service
  namespace: ecommerce-master
  labels:
    app: shipping-service
    environment: master
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: shipping-service
